name: Update Snapshots

on:
  workflow_dispatch:

permissions:
  contents: write # required for push commit
  pull-requests: write # required for gh pr create

env:
  DB_PATH: ./db.sqlite
  GH_TOKEN: ${{ github.token }}

jobs:
  update:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Setup yarn
      run: npm install -g yarn
    - name: setup node env
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn ts-node scripts/update-env.ts
    - run: yarn test -u
    - name: Commit
      run: |
        branch_name="update-snapshots-$(git rev-parse --short HEAD)"
        git config user.email "hello@acala.network"
        git config user.name "Acala Github Action Bot"
        git checkout -b $branch_name
        git commit -am 'update snapshots'
        git push origin HEAD:$branch_name
    - name: Create PR
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Update snapshots',
            head: context.repo.owner + ':' + context.ref,
            base: 'master',
            body: 'Update snapshots',
          })
